{{- $root := . -}}

{{- range $tierName, $tierValues := .Values.tiers }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ $root.Values.service.name }}-{{ $tierName }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    app: {{ $root.Values.service.name }}
    version: {{ $tierName }}
spec:
  replicas: {{ $tierValues.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
      labels:
        app: {{ $root.Values.service.name }}
        version: {{ $tierName }}
    spec:
      containers:
      - name: {{ $root.Values.service.name }}
        image: {{ $tierValues.image }}
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: {{ $tierValues.resources.requests.cpu }}
            memory: {{ $tierValues.resources.requests.memory }}
          limits:
            cpu: {{ $tierValues.resources.limits.cpu }}
            memory: {{ $tierValues.resources.limits.memory }}
        ports:
        - containerPort: {{ $tierValues.port }}
          protocol: TCP

{{ if .Values.configMap }}
        envFrom:
          - configMapRef:
               name: {{ $root.Values.service.name }}-configmap
{{ end }}

{{- end }}