apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  host: "{{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local"
  subsets:
{{- range $tierName, $tierValue := .Values.tiers }}
  - name: {{ $tierName }}
    labels:
      version: {{ $tierName }}
{{- end }}